version: '3.8'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./vue360.projets:/home/app/code/vue360.projets
    depends_on:
      - mongo_db
  mongo_db:
    image: "mongo"
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./db:/data/db
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    depends_on:
      - backend