version: '3.8'
services:
  backend:
    build:
      context: ./xxxx
      dockerfile: Dockerfile
    ports:
      - "xxxx:xxxx"
    volumes:
      - ./vue360.projets:/home/app/code/vue360.projets
    depends_on:
      - mongo_db
  mongo_db:
    image: "mongo"
    restart: always
    ports:
      - xxxx:xxxx
    volumes:
      - ./db:/data/db
  frontend:
    build:
      context: ./frontend
      dockerfile: xxxx
    ports:
      - "xxxx:xxxx"
    depends_on:
      - xxxx